name: gtfs_builder
channels:
  - conda-forge
  - anaconda
  - amauryval
dependencies:
  - python=3.9
  - flask=2.0.1
  - flask-cors=3.0.8
  - geolib=0.28.2
  - spatialpandas=0.4.3
  - python-dotenv=0.15.0
  - pytest=6.2.5
  - pytest=6.2.5
  - pytest-cov=3.0.0